### ISSUE TITLE
不會出現hello world該怎麼解決

### ISSUE THREAD

**Issue by changjaykid** [TheExplainthis/ChatGPT-Line-Bot#1]
您好想詢問操作到專案執行->開始執行那邊 點擊上方Run完後不會出現hello world該怎麼解決
只出現這個
 cowsay Configure me!
 _______________ 
< Configure me! >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 

想請教現在該怎麼做 感謝

**Comment by TheExplainthis** [comment]
你好，不知道有沒有參考文章的畫面截圖
https://www.explainthis.io/zh-hant/chatgpt/line

若還是不行，可以將畫面截圖傳上來唷！

**Comment by cosmatter** [comment]
你好~我嘗試使用了貴公司的chat gpt 的line API串接，在replit 平台下按RUN完，並未顯示HELLO WORLD，而是找不到網頁，判斷可能是貴公司關閉了伺服器或者github的code需要再修改，忽略這個問題，繼續下一步，至cronjob設定完按create後，下一步呢?我要怎麼在手機的line上找到串接好的chat gpt使用? 
感謝分享如此受用的知識，以上問題如有空再麻煩協助我解決一下，感謝囉

**Comment by as84089443** [comment]
我也有相同的問題! [https://imgur.com/a/c97djCJ](url)

**Comment by TheExplainthis** [comment]
剛剛有推了一個新版，可以在 main 中加入
```
@app.route("/", methods=['GET'])
def home():
    return 'Hello World'
```
即可

**Comment by TheExplainthis** [comment]
創建時也要選擇 python 唷！如圖所示：
<img width="483" alt="image" src="https://user-images.githubusercontent.com/97449341/221370438-c8755e7e-f1eb-47f6-a095-494333589049.png">

**Comment by FishBowl00003** [comment]
我也是，Replit Deploy Step 4 選擇Blank Repl之後不知道怎麼改回來成Python？

**Comment by specialdietitian** [comment]
我依照the explainthis重新使用python  按run 之後 出現
no such file main.py
repl press died unexpectedly: exit status 2
![image](https://user-images.githubusercontent.com/130725569/232080855-9d6b4fbb-ddc3-4c44-b889-1bee2a1fc41e.png)
