### ISSUE TITLE
對話超過一定的次數就會整個失效

### ISSUE THREAD

**Issue by Mader0801** [TheExplainthis/ChatGPT-Line-Bot#10]
![image](https://user-images.githubusercontent.com/127084068/223320000-e0bedd3e-3583-40b6-ae2f-5d76b385043f.png)

**Comment by TheExplainthis** [comment]
目前有更新至 v1.1.0 版本，建議可以直接 PR 回去，並記得修改 Environment Variable，應該可以避免這個問題。

**Comment by maxchen2k** [comment]
> 目前有更新至 v1.1.0 版本，建議可以直接 PR 回去，並記得修改 Environment Variable、更新 openai 的版本，應該可以避免這個問題。

請問 Environment Variable 要修改哪些部份？

**Comment by maxchen2k** [comment]
修改 requirements.txt & update dependence 之後還是會發生相問題

**Comment by TheExplainthis** [comment]
更新哪些變數可以從 README.md 的下半部查看，不僅是更新 openai 版本和 環境變數，最大的差異在於舊版是用 text completion 而新版是用 chat completion，所以可以連程式碼一起更新回你原本的 Repo！
