### ISSUE TITLE
請問出現405 Method Not Allowed要怎麼處理呢?

### ISSUE THREAD

**Issue by FishBowl00003** [TheExplainthis/ChatGPT-Line-Bot#14]
Perform test run: ChatGPT-Line-Bot
TEST RUN STATUS
405 Method Not Allowed

請問出現405 Method Not Allowed要怎麼處理呢?謝謝

P.s.在LINE develop
Webhook settings
Webhook URL 
https://ChatGPT-Line-Bot-1.XXXXX.repl.co/callback
按下 verify之後顯示Success

**Comment by TheExplainthis** [comment]
請問是在什麼狀況下出現 405 Method Not Allowed 呢？
會出現這個錯誤訊息表示，你的 API 並沒有相對應的 Method，舉例來說 你的 /callback 只有 POST 這個 Method，所以你把網址貼到瀏覽器上會錯誤，因為並沒有 GET 的 Method
