### ISSUE TITLE
會出現 ERROR 在 callback

### ISSUE THREAD

**Issue by renfu-her** [TheExplainthis/ChatGPT-Line-Bot#15]
INFO     chatgpt_logger -> Ua2e9625792a9f7f39d2870c2757a9027: 會哦
Ua2e9625792a9f7f39d2870c2757a9027
[2023-03-13 07:40:19,353] ERROR in app: Exception on /callback [POST]

這是發生什麽事了呢？可以幫我處理嗎？謝謝

**Comment by renfu-her** [comment]
直接拉出 uid，callback 直接由錯誤

**Comment by FishBowl00003** [comment]
我也是遇到這問題，根本無法用QQ

**Comment by TheExplainthis** [comment]
可以參考本 Repository 的 README ，有更新 gpt-3.5-turbo 的程式碼版本，環境變數也需要修改！（建議直接重新拉一個新版回去）
