### ISSUE TITLE
bot無法正常回復

### ISSUE THREAD

**Issue by ShowUNow** [TheExplainthis/ChatGPT-Line-Bot#17]
首先，我沒在教程中看到OPENAI_API應該填寫在哪裏。是Tools當中的Secrets裏面嗎？

然後我在replit中，按教程配置好，點擊run之後，雖然沒有error的報錯，但是bot無法正常回復，只能重複我的user id...
![image](https://user-images.githubusercontent.com/114962931/226912948-6e0f8e19-b1f8-48f4-a7f9-50d94f83637d.png)

我只是一個學生，希望有懂的可以幫幫我！

**Comment by TheExplainthis** [comment]
請問有將網址 + /callback 丟回去給 Line 後台的 webhook 嗎？
