### ISSUE TITLE
無法正常回復

### ISSUE THREAD

**Issue by Charley-Wu** [TheExplainthis/ChatGPT-Line-Bot#18]
各位先進好，當我所有都按照教學設定好後，輸入文字得到的回覆卻是LINE Developer的Your user ID，想請問該如何解決？
![image](https://user-images.githubusercontent.com/66875219/226929582-0ed62225-bab3-4801-9162-67d362a82893.png)

**Comment by TheExplainthis** [comment]
可以貼一下程式碼嗎？感謝
