### ISSUE TITLE
Repl 找不到 Import from Github

### ISSUE THREAD

**Issue by insanebasil** [TheExplainthis/ChatGPT-Line-Bot#26]
1. Repl 頁面 -> 點擊「create」
2. Create a Repl 彈窗 -> 沒有 「Import from Github」可以點擊
![image](https://user-images.githubusercontent.com/48146523/229389555-8f1f1da9-729d-4c2d-929d-f930aa8afbd7.png)

**Comment by davidteng00000** [comment]
我也是qwq

**Comment by TheExplainthis** [comment]
再次測試後，目前 Replit 仍有這個按鈕。可以試著重新整理頁面～
