### ISSUE TITLE
按下Run之後沒有出現hello world

### ISSUE THREAD

**Issue by as84089443** [TheExplainthis/ChatGPT-Line-Bot#3]
 cowsay Configure me!
 _______________ 
< Configure me! >
 --------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 

---------------------------
只出現以上資訊，截圖在這
https://imgur.com/a/c97djCJ

**Comment by TheExplainthis** [comment]
剛剛有推了一個新版，可以在 main 中加入
```
@app.route("/", methods=['GET'])
def home():
    return 'Hello World'
```
即可

**Comment by as84089443** [comment]
複製了新版的Main.py代碼貼上後，一樣沒有顯示呢?! 我需要整個專案重來嗎?
https://imgur.com/a/oFzCSm6

**Comment by TheExplainthis** [comment]
創建時語言需要選擇 python 唷! 如圖所示
<img width="483" alt="image" src="https://user-images.githubusercontent.com/97449341/221370424-9e5f05be-0015-42f4-a39c-e52aefe50348.png">

**Comment by as84089443** [comment]
原來如此...
圖文教學裡面是Blank Repl，改成Python就可以了!
https://www.explainthis.io/zh-hant/chatgpt/line
