### ISSUE TITLE
secret設定完之後，沒跑出網址，出現Configure me!，不知哪一步出錯

### ISSUE THREAD

**Issue by chyuhsuan** [TheExplainthis/ChatGPT-Line-Bot#7]
<img width="737" alt="Screenshot 2023-03-06 at 9 22 32 PM" src="https://user-images.githubusercontent.com/39978470/223122193-d6dfd415-799a-406a-ada3-8be92ccac4f3.png">

**Comment by TheExplainthis** [comment]
可以參考這個 issue 唷！
https://github.com/TheExplainthis/ChatGPT-Line-Bot/issues/1

**Comment by chyuhsuan** [comment]
已解決，謝謝！

**Comment by chyuhsuan** [comment]
現在全部設定完進入聊天之後，開始聊天後卻沒有反應，不知有可能是哪步驟出錯

<img width="558" alt="Screenshot 2023-03-07 at 12 33 17 PM" src="https://user-images.githubusercontent.com/39978470/223321496-5dff7953-1e81-4205-8bbe-f7950380e21d.png">

**Comment by TheExplainthis** [comment]
有沒有開啟自動回覆呢？
<img width="801" alt="image" src="https://user-images.githubusercontent.com/97449341/223324389-4c856af6-ed82-4a79-b7a0-c1b3b179fe75.png">

**Comment by chyuhsuan** [comment]
有的，這個有關掉。若打開它會自動回覆如下訊息：

感謝您的訊息！

很抱歉，本帳號無法個別回覆用戶的訊息。
敬請期待我們下次發送的內容喔(moon smile)

**Comment by TheExplainthis** [comment]
可以試著在 function 裡面加入一些 log，先判斷一下問題是以下哪一種：
1. 沒收到訊息
2. 模型有問題所以程式碼執行中斷無法回傳訊息
3. 模型沒問題，但回傳訊息時出問題
