### ISSUE TITLE
LINE裡的設定疑似有誤

### ISSUE THREAD

**Issue by haotim1989** [TheExplainthis/ChatGPT-Line-Bot#8]
「更新」
隔天早上沒動任何設定，心血來潮再問一次就正常有反應了，感謝各位大神幫助～

「原始問題如下」
你好，照著您的設定有成功出現Hello World並將Webhook URL加上/callback貼到Line Developer
也使用了CronJob 定時發送請求，但不曉得為什麼一開始它都已讀不理我

![image](https://user-images.githubusercontent.com/127127092/223174605-4742cb24-c4cd-4b17-8d89-341c60c67d8b.png)

在想是不是我的自動回覆設定那邊有誤，一開始是關掉自動回覆功能
目前的後台設定如圖

![image](https://user-images.githubusercontent.com/127127092/223174839-92022dbe-2d22-4db4-a671-1960f4be0467.png)
![image](https://user-images.githubusercontent.com/127127092/223174989-25509ebf-f702-4eca-8dac-464fabbb5449.png)

就在我亂試設定亂打的時候感覺突然出現了成功的回覆
不確定是不是單純的LAG?  但這個回覆的時間差也不知道是哪一步是成功的
再煩請協助解惑謝謝。

![image](https://user-images.githubusercontent.com/127127092/223175436-92322e25-cf16-4b10-a33a-6107f8bd3d3a.png)

**Comment by Mader0801** [comment]
原本也是都無回應，按照上面方式，就可以了，但是詢問時都不會變成已讀狀態
