### ISSUE TITLE
can only run when removed system message

### ISSUE THREAD

**Issue by chiachichi** [TheExplainthis/ChatGPT-Line-Bot#9]
As the title:
the code can only run when I removed initialize func
```
def initialize(self, user_id: str):
    self.storage[user_id] = [{
        'role': 'system', 'content': self.system_message
    }]
```

**Comment by TheExplainthis** [comment]
Could you please share the error message? Thank you.

**Comment by sidneyzz** [comment]
As a new environment variable SYSTEM_MESSAGE has been added in the updated gpt-3.5-turbo model(5eda54d) version, if this environment variable is not added in the secret of Replit, it will result in an openai.error.InvalidRequestError: None is not of type 'string' - 'messages.0.content' error.

**Comment by TheExplainthis** [comment]
Other than setting the Environment Variable, is there an update to the code for version v1.1.0? The main difference is that the old version uses text completion while the new version uses chat completion, so there are changes in the code as well.
